name: Erlang CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:27

    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: erlc ..\..\src\src\main\java\hellohi.erl
    - name: Run tests
      run: rebar3 do eunit, ct
