name: Fortify AST Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '36 3 * * 6'
  workflow_dispatch:

jobs:
  Fortify-AST-Scan:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v4

      # Install Erlang and rebar3
      - name: Setup Erlang and Rebar3
        run: |
          sudo apt-get update
          sudo apt-get install -y erlang rebar3

      # Build Erlang application using rebar3
      - name: Build Application
        run: |
          rebar3 compile

      # Package the application and dependencies for analysis
      - name: Package Application
        run: |
          mkdir fortify-package
          cp -r src/ include/ _build/ fortify-package/
          tar -czf fortify-package.tar.gz fortify-package

      # Run Fortify SAST Scan
      - name: Run FoD SAST Scan
        uses: fortify/github-action@a92347297e02391b857e7015792cd1926a4cd418
        with:
          sast-scan: true
        env:
          FOD_URL: https://ams.fortify.com
          FOD_TENANT: ${{secrets.FOD_TENANT}}
          FOD_USER: ${{secrets.FOD_USER}}
          FOD_PASSWORD: ${{secrets.FOD_PAT}}
          EXTRA_PACKAGE_OPTS: -bv fortify-package.tar.gz
          DO_WAIT: true
          DO_EXPORT: true
